import React from 'react';
import { fmtDate } from './teachers.utils';

/**
 * Hidden printable welcome letter — renders into the DOM only when
 * the user clicks "Print welcome letter". Uses `@media print` to
 * isolate it from the rest of the page.
 */
export default function WelcomeLetter({ school, teacher, credentials, onClose }) {
  const fullName = [teacher.first_name, teacher.middle_name, teacher.last_name].filter(Boolean).join(' ');
  const print = () => window.print();
  return (
    <>
      <style>{`
        @media print {
          body * { visibility: hidden; }
          .tea-letter, .tea-letter * { visibility: visible; }
          .tea-letter { position: absolute; inset: 0; padding: 28mm 22mm; background: #fff; color: #000; }
          .tea-letter__close, .tea-letter__print { display: none !important; }
        }
      `}</style>

      <div className="ska-modal-overlay" onClick={onClose}>
        <div className="tea-letter" onClick={e => e.stopPropagation()}>
          <button className="tea-letter__close" onClick={onClose} aria-label="Close">×</button>

          <header className="tea-letter__head">
            <div className="tea-letter__logo">PRUH · EK-SMS</div>
            <div className="tea-letter__sch">
              <strong>{school?.name || 'School'}</strong>
              {school?.email && <span>{school.email}</span>}
              <span>Issued: {fmtDate(new Date().toISOString().slice(0, 10))}</span>
            </div>
          </header>

          <h1 className="tea-letter__title">Welcome to the team, {teacher.first_name || 'colleague'}!</h1>

          <p className="tea-letter__para">
            Dear <strong>{fullName}</strong>,
          </p>
          <p className="tea-letter__para">
            We are delighted to confirm your appointment at <strong>{school?.name}</strong>.
            Your staff record has been created and your access to the EK-SMS portal is now active.
          </p>

          <h3 className="tea-letter__h3">Your account credentials</h3>
          <table className="tea-letter__creds">
            <tbody>
              <tr><th>Login URL</th><td>{credentials?.login_url || window.location.origin}</td></tr>
              <tr><th>Email</th><td>{credentials?.email || teacher.email}</td></tr>
              <tr><th>Username</th><td>{credentials?.login_username || '—'}</td></tr>
              <tr><th>Temporary password</th><td><code>{credentials?.password || '••••••••'}</code></td></tr>
              <tr><th>Employee ID</th><td>{teacher.employee_id || '—'}</td></tr>
              <tr><th>Hire date</th><td>{fmtDate(teacher.hire_date)}</td></tr>
            </tbody>
          </table>

          <p className="tea-letter__note">
            <strong>Important:</strong> for security, you will be required to change your password the first time you sign in.
            Keep this letter confidential and do not share your credentials.
          </p>

          <h3 className="tea-letter__h3">First-day checklist</h3>
          <ul className="tea-letter__list">
            <li>Sign in at the URL above and update your password.</li>
            <li>Review the classes &amp; subjects assigned to you.</li>
            <li>Confirm your weekly availability and any timetable conflicts.</li>
            <li>Upload any pending documents (license, clearance) under your profile.</li>
          </ul>

          <p className="tea-letter__sign">
            With warm regards,<br />
            <strong>The {school?.name || 'School'} Administration</strong>
          </p>

          <footer className="tea-letter__foot">
            Generated by EK-SMS · {fmtDate(new Date().toISOString().slice(0, 10))}
          </footer>

          <div className="tea-letter__print">
            <button className="ska-btn ska-btn--ghost" onClick={onClose}>Close</button>
            <button className="ska-btn ska-btn--primary" onClick={print}>
              <span className="ska-icon ska-icon--sm">print</span> Print
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
