# Generated by Django 4.2.13 on 2026-02-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport_picture',
            field=models.ImageField(blank=True, help_text='Student passport/ID photo', null=True, upload_to='student_passports/'),
        ),
    ]
