# Generated by Django 4.2.13 on 2026-02-22 20:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eksms_core', '0002_student_passport_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_subjects', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('class_size', models.IntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='report_cards/')),
                ('qr_code', models.CharField(blank=True, help_text='QR code for verification', max_length=255, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False, help_text='Can parents view this report card?')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eksms_core.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eksms_core.classroom')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='eksms_core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eksms_core.term')),
            ],
            options={
                'verbose_name_plural': 'Report Cards',
                'ordering': ['-academic_year', '-term'],
                'unique_together': {('student', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuous_assessment', models.DecimalField(decimal_places=2, default=0, help_text='Continuous Assessment / Class Work (0-20)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('mid_term_exam', models.DecimalField(decimal_places=2, default=0, help_text='Mid-term Exam Score (0-30)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_exam', models.DecimalField(decimal_places=2, default=0, help_text='Final Exam Score (0-50)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_score', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated: CA + Mid-term + Final (max 100)', max_digits=5)),
                ('grade_letter', models.CharField(choices=[('A', 'A (90-100)'), ('B', 'B (80-89)'), ('C', 'C (70-79)'), ('D', 'D (60-69)'), ('E', 'E (0-59)'), ('I', 'Incomplete')], default='I', help_text='Auto-calculated letter grade', max_length=1)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked grades cannot be edited')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='eksms_core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eksms_core.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eksms_core.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='eksms_core.term')),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'ordering': ['student', 'subject'],
                'indexes': [models.Index(fields=['student', 'term'], name='eksms_core__student_7a239b_idx'), models.Index(fields=['subject', 'term'], name='eksms_core__subject_e1bcd9_idx')],
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ClassRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='Rank in class (1 is top)')),
                ('total_points', models.DecimalField(decimal_places=2, help_text='Sum of all subject grades', max_digits=7)),
                ('average_score', models.DecimalField(decimal_places=2, help_text='Average across all subjects', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='eksms_core.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eksms_core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eksms_core.term')),
            ],
            options={
                'verbose_name_plural': 'Class Rankings',
                'ordering': ['term', 'rank'],
                'unique_together': {('classroom', 'student', 'term')},
            },
        ),
    ]
