# Generated by Django 4.2.13 on 2026-02-22 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eksms_core', '0003_reportcard_grade_classranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_token', models.CharField(db_index=True, help_text='Unique token for verification', max_length=256, unique=True)),
                ('qr_code_data', models.TextField(help_text='Encoded data in QR code')),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('merkle_leaf', models.CharField(help_text="This record's Merkle tree leaf", max_length=64)),
                ('merkle_root', models.CharField(db_index=True, help_text='Merkle root of all grades up to this point', max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(help_text='Verification expires after this date')),
                ('verification_attempts', models.IntegerField(default=0)),
                ('last_verification_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='eksms_core.grade')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Grade Verifications',
            },
        ),
        migrations.CreateModel(
            name='GradeChangeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Low - Minor edit'), ('MEDIUM', 'Medium - Significant change'), ('HIGH', 'High - Major alteration'), ('CRITICAL', 'Critical - Locked grade modified')], max_length=20)),
                ('alert_type', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('NEW', 'New Alert'), ('ACKNOWLEDGED', 'Acknowledged'), ('INVESTIGATED', 'Investigated'), ('RESOLVED', 'Resolved'), ('FALSE_ALARM', 'False Alarm')], db_index=True, default='NEW', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('investigation_notes', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_to', models.EmailField(blank=True, max_length=254)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_alerts', to='eksms_core.grade')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Grade Change Alerts',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['grade', '-triggered_at'], name='eksms_core__grade_i_9ee987_idx'), models.Index(fields=['severity', '-triggered_at'], name='eksms_core__severit_3184d6_idx'), models.Index(fields=['status'], name='eksms_core__status_8f93ad_idx'), models.Index(fields=['triggered_by', '-triggered_at'], name='eksms_core__trigger_e608d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Grade Created'), ('UPDATE', 'Grade Updated'), ('LOCK', 'Grade Locked'), ('UNLOCK', 'Grade Unlocked'), ('VIEW', 'Grade Viewed'), ('DELETE_ATTEMPT', 'Delete Attempt'), ('ARCHIVE', 'Grade Archived')], max_length=20)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous values before this change', null=True)),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New values after this change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client info')),
                ('change_reason', models.TextField(blank=True, help_text='Why was this change made?')),
                ('record_hash', models.CharField(db_index=True, help_text='SHA256 hash of record for integrity', max_length=256)),
                ('merkle_hash', models.CharField(db_index=True, help_text='Merkle tree hash including all previous records', max_length=256)),
                ('logged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='eksms_core.grade')),
            ],
            options={
                'verbose_name_plural': 'Grade Audit Logs',
                'ordering': ['grade', '-logged_at'],
                'indexes': [models.Index(fields=['grade', '-logged_at'], name='eksms_core__grade_i_6f3933_idx'), models.Index(fields=['actor', '-logged_at'], name='eksms_core__actor_i_51ff6b_idx'), models.Index(fields=['action', '-logged_at'], name='eksms_core__action_d875a9_idx'), models.Index(fields=['record_hash'], name='eksms_core__record__38b5f4_idx')],
            },
        ),
    ]
