# Generated by Django 4.2.13 on 2026-02-23 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eksms_core', '0004_gradeverification_gradechangealert_gradeauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='School name', max_length=255, unique=True)),
                ('code', models.CharField(help_text='School code/ID', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='School contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='School contact phone', max_length=20)),
                ('address', models.TextField(blank=True, help_text='School physical address')),
                ('principal_name', models.CharField(blank=True, help_text='Principal/Head of School name', max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this school active in the system?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Super admin who registered this school', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(help_text='e.g., 2024-2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(help_text='Unique code within school', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(help_text='Must be unique per school', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='Subject code', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Subject name', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(help_text='Must be unique per school', max_length=50),
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, help_text='e.g., School Administrator, Headmaster', max_length=100)),
                ('can_manage_teachers', models.BooleanField(default=True, help_text='Can manage teacher accounts and assignments')),
                ('can_manage_students', models.BooleanField(default=True, help_text='Can manage student registrations')),
                ('can_manage_grades', models.BooleanField(default=True, help_text='Can manage grading system')),
                ('can_manage_reports', models.BooleanField(default=True, help_text='Can generate and publish reports')),
                ('can_manage_academics', models.BooleanField(default=True, help_text='Can manage academic years, terms, and classes')),
                ('can_view_audit_logs', models.BooleanField(default=False, help_text='Can view audit logs')),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='eksms_core.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Admin',
                'verbose_name_plural': 'School Admins',
            },
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='eksms_core.school'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='eksms_core.school'),
        ),
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='eksms_core.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='eksms_core.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='eksms_core.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='eksms_core.school'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'admission_number')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('school', 'employee_id')},
        ),
    ]
