# Generated by Django 4.2.13 on 2026-02-23 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eksms_core', '0005_school_alter_academicyear_name_alter_classroom_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian'), ('STAFF', 'Administrative Staff'), ('ACCOUNTANT', 'Accountant'), ('REGISTRAR', 'Registrar'), ('LIBRARIAN', 'Librarian'), ('COUNSELOR', 'Counselor')], help_text='Staff member role/position', max_length=20)),
                ('job_title', models.CharField(blank=True, help_text='Job title/position (e.g., Mathematics Teacher)', max_length=150)),
                ('department', models.CharField(blank=True, help_text='Department (e.g., Science, Administration)', max_length=100)),
                ('can_create_announcements', models.BooleanField(default=False, help_text='Can post announcements')),
                ('can_submit_assignments', models.BooleanField(default=False, help_text='Can submit assignments')),
                ('can_view_results', models.BooleanField(default=False, help_text='Can view grades/results')),
                ('can_edit_content', models.BooleanField(default=False, help_text='Can modify educational content')),
                ('is_active', models.BooleanField(default=True, help_text='Is this staff account active?')),
                ('account_status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='PENDING', help_text='Current status of the staff account', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When was this account activated?', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_accounts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_account', to='eksms_core.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_accounts', to='eksms_core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_account', to='eksms_core.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_account', to='eksms_core.teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_staff_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Staff Account',
                'verbose_name_plural': 'School Staff Accounts',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_staff_accounts', 'Can approve pending staff accounts'), ('can_suspend_staff', 'Can suspend staff accounts')],
                'unique_together': {('user', 'school')},
            },
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='can_activate_deactivate_staff',
            field=models.BooleanField(default=True, help_text='Can activate/deactivate staff accounts'),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='can_create_staff_accounts',
            field=models.BooleanField(default=True, help_text='Can create and manage staff accounts (teachers, etc.)'),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='can_manage_parents',
            field=models.BooleanField(default=True, help_text='Can manage parent/guardian accounts and links'),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='can_manage_staff_roles',
            field=models.BooleanField(default=True, help_text='Can assign and modify staff member roles'),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='can_manage_grades',
            field=models.BooleanField(default=True, help_text='Can manage grading system and enter grades'),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='can_manage_students',
            field=models.BooleanField(default=True, help_text='Can manage student registrations and enrollments'),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='can_manage_teachers',
            field=models.BooleanField(default=True, help_text='Can manage teacher records and assignments'),
        ),
        migrations.CreateModel(
            name='StaffAccountAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Account Created'), ('ACTIVATED', 'Account Activated'), ('UPDATED', 'Account Updated'), ('SUSPENDED', 'Account Suspended'), ('TERMINATED', 'Account Terminated'), ('ROLE_CHANGED', 'Role Changed'), ('PERMISSIONS_CHANGED', 'Permissions Changed')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Details of the change')),
                ('old_values', models.JSONField(blank=True, help_text='Previous values before change', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values after change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_audit_changes', to=settings.AUTH_USER_MODEL)),
                ('staff_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='eksms_core.schoolstaffaccount')),
            ],
            options={
                'verbose_name': 'Staff Account Audit Log',
                'verbose_name_plural': 'Staff Account Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
