# Generated by Django 4.2.13 on 2026-02-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0006_schoolstaffaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Has this school been reviewed and approved by a super admin?'),
        ),
    ]
