# Generated by Django 6.0.1 on 2026-03-02 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0008_school_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='continuous_assessment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Continuous Assessment / Class Work (0-20)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_exam',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final Exam Score (0-50)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='mid_term_exam',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mid-term Exam Score (0-30)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
