# Generated by Django 6.0.1 on 2026-03-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0009_add_grade_score_max_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waitlist Email',
                'verbose_name_plural': 'Waitlist Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
