# Generated by Django 6.0.3 on 2026-03-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0011_school_more_extended_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Recipient email address', max_length=254)),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the 6-digit OTP', max_length=64)),
                ('expires_at', models.DateTimeField(help_text='When this OTP stops being valid')),
                ('is_used', models.BooleanField(default=False, help_text='True once the OTP has been verified')),
                ('attempts', models.IntegerField(default=0, help_text='Number of failed verification attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Record',
                'verbose_name_plural': 'OTP Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
