# Generated by Django 6.0.1 on 2026-03-24 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0013_new_endpoint_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemWideAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('grade_lock_attempt', 'Grade Modification on Locked Record'), ('enrollment_change', 'Student Enrollment Status Change'), ('fee_payment', 'Fee Payment Recorded'), ('attendance_anomaly', 'Attendance Anomaly Detected'), ('permission_change', 'User Permission Change')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='new', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('notif_in_app', models.BooleanField(default=True)),
                ('notif_email', models.BooleanField(default=False)),
                ('notif_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notif_sms', models.BooleanField(default=False)),
                ('notif_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notif_push', models.BooleanField(default=False)),
                ('notif_push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_system_alerts', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_alerts', to='eksms_core.school')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_system_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Wide Alert',
                'verbose_name_plural': 'System Wide Alerts',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['trigger_type', '-triggered_at'], name='eksms_core__trigger_972ecb_idx'), models.Index(fields=['severity', '-triggered_at'], name='eksms_core__severit_9894cb_idx'), models.Index(fields=['status'], name='eksms_core__status_3348c4_idx')],
            },
        ),
    ]
