# Generated by Django 6.0.1 on 2026-03-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0016_exam_examresult_notification_notificationread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolstaffaccount',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian'), ('STAFF', 'Administrative Staff'), ('ACCOUNTANT', 'Accountant'), ('PRINCIPAL', 'Principal'), ('REGISTRAR', 'Registrar'), ('LIBRARIAN', 'Librarian'), ('COUNSELOR', 'Counselor')], help_text='Staff member role/position', max_length=20),
        ),
    ]
