# Generated by Django 6.0.1 on 2026-03-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0017_alter_schoolstaffaccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Teacher profile photo', null=True, upload_to='teacher_photos/'),
        ),
    ]
