# Generated by Django 6.0.1 on 2026-04-18 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0018_add_student_gender_teacher_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_user',
            field=models.ForeignKey(blank=True, help_text='If set, only this user sees the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='verification_hash',
            field=models.CharField(blank=True, help_text='SHA256 of report card data', max_length=64),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force password change on next login'),
        ),
        migrations.AddField(
            model_name='student',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='grade_entry_deadline',
            field=models.DateTimeField(blank=True, help_text='Hard deadline for grade entry', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='grade_entry_open',
            field=models.BooleanField(default=False, help_text='Teachers can enter grades when True'),
        ),
        migrations.AddField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_letter',
            field=models.CharField(choices=[('A+', 'A+ (90-100)'), ('A', 'A  (80-89)'), ('B', 'B  (70-79)'), ('C', 'C  (60-69)'), ('D', 'D  (50-59)'), ('F', 'F  (0-49)'), ('I', 'Incomplete')], default='I', help_text='Auto-calculated letter grade', max_length=2),
        ),
        migrations.AlterField(
            model_name='gradeauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Grade Created'), ('UPDATE', 'Grade Updated'), ('SUBMIT', 'Submitted for Locking'), ('LOCK', 'Grade Locked'), ('UNLOCK', 'Grade Unlocked'), ('VIEW', 'Grade Viewed'), ('MODIFICATION_ATTEMPT', 'Unauthorised Modification Attempt'), ('MOD_REQUEST', 'Modification Request Submitted'), ('MOD_APPROVED', 'Modification Request Approved'), ('MOD_REJECTED', 'Modification Request Rejected'), ('DELETE_ATTEMPT', 'Delete Attempt'), ('ARCHIVE', 'Grade Archived')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_passports/'),
        ),
        migrations.CreateModel(
            name='GradeModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proposed_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(help_text='Detailed reason for the modification request')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='mod_evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=10)),
                ('review_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_requests', to='eksms_core.grade')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_mod_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_mod_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade Modification Request',
                'verbose_name_plural': 'Grade Modification Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Token',
                'verbose_name_plural': 'User Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='eksms_core.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='eksms_core.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='eksms_core.subject')),
            ],
            options={
                'verbose_name': 'Class Subject',
                'verbose_name_plural': 'Class Subjects',
                'ordering': ['classroom', 'subject__name'],
                'unique_together': {('classroom', 'subject', 'academic_year')},
            },
        ),
    ]
