# Generated by Django 6.0.1 on 2026-04-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0019_notification_recipient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_examination_officer',
            field=models.BooleanField(default=False, help_text='Can generate and publish report cards'),
        ),
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_mark', models.PositiveSmallIntegerField(default=50, help_text='Minimum score to pass (out of 100)')),
                ('boundaries', models.JSONField(default=list, help_text='Grade boundary definitions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scheme', to='eksms_core.school')),
            ],
            options={
                'verbose_name': 'Grading Scheme',
                'verbose_name_plural': 'Grading Schemes',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('library', 'Library'), ('hall', 'Assembly Hall'), ('gymnasium', 'Gymnasium'), ('other', 'Other')], default='classroom', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='eksms_core.school')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
