# Generated by Django 6.0.1 on 2026-04-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0020_add_room_gradingscheme_examofficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived years are read-only historical records'),
        ),
    ]
