# Generated by Django 6.0.1 on 2026-04-22 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0021_academicyear_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentstudent',
            name='relationship_type',
            field=models.CharField(blank=True, help_text='e.g., Mother, Father, Guardian', max_length=50),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='principal_comment',
            field=models.TextField(blank=True, help_text="Principal's comments"),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='teacher_comment',
            field=models.TextField(blank=True, help_text="Class teacher's comments"),
        ),
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies'),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_type',
            field=models.CharField(blank=True, help_text='e.g., A+, O-', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='General medical notes / conditions'),
        ),
        migrations.AlterField(
            model_name='securitylogentry',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('permission_changed', 'Permission Changed'), ('school_approved', 'School Approved'), ('school_rejected', 'School Rejected'), ('broadcast_sent', 'Broadcast Sent'), ('suspicious_activity', 'Suspicious Activity'), ('api_rate_limited', 'API Rate Limited'), ('profile_updated', 'Profile Updated'), ('student_transfer', 'Student Transfer'), ('academic_year_archived', 'Academic Year Archived')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ParentNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('grade_alerts', models.BooleanField(default=True)),
                ('attendance_alerts', models.BooleanField(default=True)),
                ('fee_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='eksms_core.parent')),
            ],
            options={
                'verbose_name': 'Parent Notification Preference',
                'verbose_name_plural': 'Parent Notification Preferences',
            },
        ),
    ]
