# Generated by Django 6.0.1 on 2026-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0022_parentstudent_relationship_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('suspended', 'Suspended'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='active', max_length=20),
        ),
    ]
