# Generated by Django 6.0.1 on 2026-04-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0023_add_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_category',
            field=models.CharField(blank=True, choices=[('full_paying', 'Full-Paying'), ('partial_scholarship', 'Partial Scholarship'), ('full_scholarship', 'Full Scholarship'), ('government_sponsored', 'Government-Sponsored'), ('bursary', 'Bursary')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='home_language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(blank=True, choices=[('day', 'Day Student'), ('boarding', 'Boarding / Hostel')], default='day', max_length=20),
        ),
    ]
