# Generated by Django 6.0.1 on 2026-04-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0026_add_middle_name_hostel_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sen_iep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='sen_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_route',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
