# Generated by Django 6.0.1 on 2026-04-26 23:29
# Renumbered from 0023 to 0028 to follow local migration chain (0023-0027).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0027_add_transport_sen_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disciplinary_history',
            field=models.BooleanField(default=False, help_text='Has the student ever been suspended or expelled?'),
        ),
        migrations.AddField(
            model_name='student',
            name='disciplinary_notes',
            field=models.TextField(blank=True, help_text='Details about disciplinary incidents, if any.'),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('passport_photo', 'Passport Photograph'), ('previous_school_report', 'Previous School Report'), ('transfer_letter', 'Transfer Letter'), ('medical_report', 'Medical Report'), ('other', 'Other Document')], max_length=50)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='eksms_core.student')),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'ordering': ['student', 'document_type'],
                'unique_together': {('student', 'document_type')},
            },
        ),
    ]
