# Generated by Django 6.0.1 on 2026-05-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0035_classroom_curriculum_schedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='liveclass',
            new_name='eksms_core__classro_d09161_idx',
            old_name='lc_class_start_idx',
        ),
        migrations.RenameIndex(
            model_name='liveclass',
            new_name='eksms_core__teacher_498028_idx',
            old_name='lc_teach_start_idx',
        ),
        migrations.RenameIndex(
            model_name='liveclass',
            new_name='eksms_core__school__db445d_idx',
            old_name='lc_school_status_idx',
        ),
    ]
