# Generated by Django 6.0.1 on 2026-05-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0035_classroom_curriculum_schedule'),
    ]

    operations = [
        # This migration is now a no-op because the same LiveClass index rename
        # has already been performed by 0037_rename_lc_class_start_idx_eksms_core__classro_d09161_idx_and_more.
    ]
