# Generated by Django 6.0.1 on 2026-05-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0036_fix_student_place_of_birth_and_verification_token'),
        ('eksms_core', '0036_rename_lc_class_start_idx_eksms_core__classro_d09161_idx_and_more'),
    ]

    operations = [
    ]
