# Generated by Django 6.0.1 on 2026-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0036_fix_student_place_of_birth_and_verification_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='liveclass',
            new_name='eksms_core__classro_d09161_idx',
            old_name='lc_class_start_idx',
        ),
        migrations.RenameIndex(
            model_name='liveclass',
            new_name='eksms_core__teacher_498028_idx',
            old_name='lc_teach_start_idx',
        ),
        migrations.RenameIndex(
            model_name='liveclass',
            new_name='eksms_core__school__db445d_idx',
            old_name='lc_school_status_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='is_critical_medical',
            field=models.BooleanField(default=False, help_text='Requires critical medical attention'),
        ),
        migrations.AddField(
            model_name='student',
            name='sen_tier',
            field=models.CharField(blank=True, help_text='SEN support tier', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='vaccinations',
            field=models.JSONField(blank=True, default=dict, help_text='Vaccination records {vaccine: date}'),
        ),
    ]
