# Generated by Django 6.0.1 on 2026-05-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eksms_core', '0037_merge_20260506_1526'),
        ('eksms_core', '0037_rename_lc_class_start_idx_eksms_core__classro_d09161_idx_and_more'),
    ]

    operations = [
    ]
