import React, { useState } from 'react';

/* ---- Icons ---- */
const IcBack   = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/></svg>;
const IcShield = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>;
const IcCheck  = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>;
const IcXCirc  = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/></svg>;
const IcFlag   = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><line x1="4" y1="22" x2="4" y2="15"/></svg>;
const IcArrow  = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>;
const IcNet    = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 010 20M12 2a15.3 15.3 0 000 20"/></svg>;

const SEVERITY_CFG = {
  critical: { label: 'Critical', color: 'var(--sa-red)',    bg: 'var(--sa-red-dim)'    },
  high:     { label: 'High',     color: 'var(--sa-amber)',  bg: 'var(--sa-amber-dim)'  },
  medium:   { label: 'Medium',   color: 'var(--sa-accent)', bg: 'var(--sa-accent-dim)' },
  low:      { label: 'Low',      color: 'var(--sa-purple)', bg: 'var(--sa-purple-dim)' },
  info:     { label: 'Info',     color: 'var(--sa-green)',  bg: 'var(--sa-green-dim)'  },
};

const MOCK_CASES = [
  {
    id: 'FR-2026-001', severity: 'critical', type: 'Grade Tamper',
    desc: 'Unauthorized edit attempt on locked grade records',
    actor: 'teacher_jb@mab', ip: '192.168.1.45', ts: '2026-02-28 23:14:02',
    status: 'Open',
    corruptHash: '7f8a9bc0d1e2f3a4b59c3d7e6f012345', backupHash: '4a2b1cc0d1e2f3a4b59c3d7e6f012345',
  },
  {
    id: 'FR-2026-002', severity: 'high', type: 'Brute Force',
    desc: 'Repeated login failures from external IP — 48 attempts in 3 minutes',
    actor: 'Unknown', ip: '77.91.230.14', ts: '2026-02-28 19:22:33',
    status: 'Open',
    corruptHash: null, backupHash: null,
  },
  {
    id: 'FR-2026-003', severity: 'high', type: 'Hash Mismatch',
    desc: 'Database integrity check failed on student grade table row #4419',
    actor: 'ID-9921', ip: '10.0.0.211', ts: '2026-02-28 22:51:19',
    status: 'Resolved',
    corruptHash: 'a3f9d1b2c8e04f712345abcdef678901', backupHash: 'a3f9d1b2c8e04f712345abcdef678901',
  },
  {
    id: 'FR-2026-004', severity: 'critical', type: 'Session Hijack',
    desc: 'Token replay attack detected from foreign origin — active admin session cloned',
    actor: 'Unknown', ip: '185.220.101.3', ts: '2026-02-28 20:00:08',
    status: 'Open',
    corruptHash: '9c2a7fe8b3d1045678abcd90ef123456', backupHash: '4a2b1cc0d1e2f34590abcd12ef789012',
  },
];

const MALICIOUS_IPS = [
  { ip: '192.168.1.45',  status: 'Active now', col: 'var(--sa-red)'   },
  { ip: '10.0.0.211',    status: '2h ago',     col: 'var(--sa-amber)' },
  { ip: '77.91.230.14',  status: '5h ago',     col: 'var(--sa-amber)' },
  { ip: '185.220.101.3', status: '4h ago',     col: 'var(--sa-red)'   },
];

const CHAIN_STEPS = [
  { label: 'Record Created',    desc: 'Original event log entry generated by backend middleware.', done: true  },
  { label: 'Hash Generated',    desc: 'SHA-256 hash computed and attached to the record.',         done: true  },
  { label: 'Merkle Node Added', desc: 'Record inserted into the Merkle integrity tree.',           done: true  },
  { label: 'Block Sealed',      desc: 'Merkle root sealed — node locked against modification.',    done: true  },
  { label: 'Integrity Check',   desc: 'Automated audit compared live hash against sealed root.',   done: false },
];

function fmtDateTime(ts) {
  if (!ts) return '—';
  return new Date(ts).toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
}

/* ==============================
   Detail (Deep-dive) view
   ============================== */
function ForensicDetail({ caseData, onBack }) {
  const [acknowledged, setAcknowledged] = useState(false);
  const cfg = SEVERITY_CFG[caseData.severity] || SEVERITY_CFG.info;
  const hasMismatch = caseData.corruptHash && caseData.corruptHash !== caseData.backupHash;

  return (
    <div style={{ maxWidth: 720, margin: '0 auto' }}>
      <button className="sa-btn sa-btn--ghost sa-btn--sm" style={{ marginBottom: 20, gap: 6 }} onClick={onBack}>
        <IcBack /> Back to Cases
      </button>

      {/* Title row */}
      <div style={{ marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginBottom: 8 }}>
          <span style={{ fontFamily: 'Consolas, monospace', fontSize: '0.75rem', color: 'var(--sa-accent)' }}>{caseData.id}</span>
          <span style={{
            background: cfg.bg, color: cfg.color, border: `1px solid ${cfg.color}33`,
            borderRadius: 6, padding: '2px 9px', fontSize: '0.6875rem', fontWeight: 700,
          }}>{cfg.label}</span>
          <span style={{
            background: caseData.status === 'Open' ? 'var(--sa-red-dim)' : 'var(--sa-green-dim)',
            color: caseData.status === 'Open' ? 'var(--sa-red)' : 'var(--sa-green)',
            borderRadius: 6, padding: '2px 9px', fontSize: '0.6875rem', fontWeight: 700,
          }}>{caseData.status}</span>
        </div>
        <h1 className="sa-page-title" style={{ marginBottom: 4 }}>Technical Evidence Log</h1>
        <p className="sa-page-sub">{caseData.desc}</p>
      </div>

      {/* Event Details */}
      <div className="sa-review-section" style={{ marginBottom: 16 }}>
        <div className="sa-review-section-head"><IcShield /> Event Details</div>
        <div className="sa-review-section-body">
          {[
            ['Timestamp',  <span style={{ fontFamily: 'Consolas, monospace', fontSize: '0.8125rem' }}>{caseData.ts}</span>],
            ['Source IP',  <span style={{ fontFamily: 'Consolas, monospace', color: caseData.severity === 'critical' ? 'var(--sa-red)' : 'var(--sa-text-2)', fontWeight: 700 }}>{caseData.ip}</span>],
            ['Event Type', caseData.type],
            ['Actor',      <span style={{ fontFamily: 'Consolas, monospace', fontSize: '0.8125rem' }}>{caseData.actor}</span>],
            ['Action',     'Write Attempt on Locked Record'],
          ].map(([k, v], i, arr) => (
            <div key={k} className="sa-review-field" style={{ borderBottom: i === arr.length - 1 ? 'none' : undefined }}>
              <span className="sa-review-field-key">{k}</span>
              <span className="sa-review-field-val">{v}</span>
            </div>
          ))}
        </div>
      </div>

      {/* SHA-256 Hash Comparison */}
      {caseData.corruptHash && (
        <div className="sa-card" style={{ marginBottom: 16 }}>
          <div className="sa-card-head">
            <p className="sa-card-title">Data Integrity Check</p>
            <span style={{
              fontFamily: 'Consolas, monospace', fontSize: '0.625rem',
              background: 'var(--sa-card-bg2)', padding: '2px 8px', borderRadius: 4, color: 'var(--sa-text-2)',
            }}>SHA-256</span>
          </div>
          <div className="sa-card-body">
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
              <div style={{ background: 'var(--sa-red-dim)', border: '1px solid rgba(239,68,68,0.2)', borderRadius: 10, padding: '12px 14px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
                  <IcXCirc style={{ width: 14, height: 14, stroke: 'var(--sa-red)' }} />
                  <span style={{ color: 'var(--sa-red)', fontSize: '0.75rem', fontWeight: 700 }}>Corrupted Record</span>
                </div>
                <div style={{ fontFamily: 'Consolas, monospace', fontSize: '0.625rem', wordBreak: 'break-all', color: 'var(--sa-text-2)', lineHeight: 1.6 }}>
                  <span style={{ background: 'rgba(239,68,68,0.3)', color: 'var(--sa-red)', padding: '0 2px', borderRadius: 2 }}>
                    {caseData.corruptHash.slice(0, 6)}
                  </span>
                  {caseData.corruptHash.slice(6)}
                </div>
              </div>
              <div style={{ background: 'var(--sa-green-dim)', border: '1px solid rgba(16,185,129,0.2)', borderRadius: 10, padding: '12px 14px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
                  <IcCheck style={{ width: 14, height: 14, stroke: 'var(--sa-green)' }} />
                  <span style={{ color: 'var(--sa-green)', fontSize: '0.75rem', fontWeight: 700 }}>System Backup</span>
                </div>
                <div style={{ fontFamily: 'Consolas, monospace', fontSize: '0.625rem', wordBreak: 'break-all', color: 'var(--sa-text-2)', lineHeight: 1.6 }}>
                  <span style={{ background: 'rgba(16,185,129,0.3)', color: 'var(--sa-green)', padding: '0 2px', borderRadius: 2 }}>
                    {caseData.backupHash.slice(0, 6)}
                  </span>
                  {caseData.backupHash.slice(6)}
                </div>
              </div>
            </div>
            {hasMismatch && (
              <div style={{ marginTop: 12, display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', background: 'var(--sa-red-dim)', borderRadius: 8, border: '1px solid rgba(239,68,68,0.2)' }}>
                <span style={{ color: 'var(--sa-red)', fontSize: '1.1rem', flexShrink: 0 }}>⚠</span>
                <p style={{ margin: 0, fontSize: '0.8125rem', color: 'var(--sa-red)', fontWeight: 600 }}>
                  Hash mismatch detected — record integrity is compromised
                </p>
              </div>
            )}
            {!hasMismatch && (
              <div style={{ marginTop: 12, display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', background: 'var(--sa-green-dim)', borderRadius: 8, border: '1px solid rgba(16,185,129,0.2)' }}>
                <IcCheck style={{ width: 16, height: 16, stroke: 'var(--sa-green)', flexShrink: 0 }} />
                <p style={{ margin: 0, fontSize: '0.8125rem', color: 'var(--sa-green)', fontWeight: 600 }}>
                  Hashes match — record integrity verified
                </p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Network Intelligence */}
      <div className="sa-card" style={{ marginBottom: 16 }}>
        <div className="sa-card-head">
          <p className="sa-card-title"><IcNet style={{ display: 'inline', verticalAlign: 'middle', width: 14, height: 14, marginRight: 6 }} />Network Intelligence</p>
        </div>
        <div className="sa-card-body">
          <p style={{ margin: '0 0 10px', fontSize: '0.75rem', fontWeight: 700, color: 'var(--sa-text-2)', textTransform: 'uppercase', letterSpacing: '0.07em' }}>
            Associated Malicious IPs
          </p>
          {MALICIOUS_IPS.map((item, i) => (
            <div key={i} style={{
              display: 'flex', justifyContent: 'space-between', alignItems: 'center',
              padding: '8px 12px', marginBottom: 6,
              background: 'var(--sa-card-bg2)', borderRadius: 8, border: '1px solid var(--sa-border)',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <span style={{ width: 8, height: 8, borderRadius: '50%', background: item.col, display: 'inline-block', flexShrink: 0 }} />
                <span style={{ fontFamily: 'Consolas, monospace', fontSize: '0.8125rem', color: 'var(--sa-text)' }}>{item.ip}</span>
              </div>
              <span style={{ fontSize: '0.75rem', color: 'var(--sa-text-2)' }}>{item.status}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Chain of Custody */}
      <div className="sa-card" style={{ marginBottom: 16 }}>
        <div className="sa-card-head"><p className="sa-card-title">Chain of Custody</p></div>
        <div className="sa-card-body" style={{ paddingBottom: 8 }}>
          <div className="sa-tl">
            {CHAIN_STEPS.map((step, i) => (
              <div key={i} className="sa-tl-item">
                <div className="sa-tl-left">
                  <div className={`sa-tl-dot sa-tl-dot--${step.done ? 'green' : 'amber'}${!step.done ? ' sa-tl-dot--pulse' : ''}`} />
                  {i < CHAIN_STEPS.length - 1 && <div className="sa-tl-line" />}
                </div>
                <div className="sa-tl-content" style={{ paddingBottom: i < CHAIN_STEPS.length - 1 ? 18 : 0 }}>
                  <p style={{ margin: '0 0 3px', fontWeight: 700, fontSize: '0.875rem', color: step.done ? 'var(--sa-text)' : 'var(--sa-amber)' }}>
                    {step.label}
                  </p>
                  <p style={{ margin: 0, fontSize: '0.8125rem', color: 'var(--sa-text-2)', lineHeight: 1.55 }}>{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Footer actions */}
      <div style={{ background: 'var(--sa-card-bg)', border: '1px solid var(--sa-border)', borderRadius: 'var(--sa-radius)', padding: '18px 20px' }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12, marginBottom: 16 }}>
          <div className="sa-stat-icon sa-stat-icon--blue" style={{ width: 36, height: 36, flexShrink: 0 }}>
            <IcShield />
          </div>
          <div>
            <p style={{ margin: '0 0 2px', fontWeight: 700, fontSize: '0.9375rem', color: 'var(--sa-text)' }}>Digitally Signed Report</p>
            <p style={{ margin: 0, fontSize: '0.75rem', color: 'var(--sa-text-2)' }}>
              Verified by SecurLog™ Integrity Protocol · Sig:{' '}
              <span style={{ fontFamily: 'Consolas, monospace', fontSize: '0.6875rem' }}>0x492...1F</span>
            </p>
          </div>
        </div>
        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
          <button className="sa-btn sa-btn--ghost" style={{ flex: 1, justifyContent: 'center' }}>
            <IcFlag /> Flag for Review
          </button>
          <button
            className={`sa-btn ${acknowledged ? 'sa-btn--ghost' : 'sa-btn--primary'}`}
            style={{ flex: 1, justifyContent: 'center' }}
            onClick={() => setAcknowledged(true)}
            disabled={acknowledged}
          >
            <IcCheck /> {acknowledged ? 'Acknowledged ✓' : 'Acknowledge & Dismiss'}
          </button>
        </div>
      </div>
    </div>
  );
}

/* ==============================
   List (Summary) view
   ============================== */
export default function SAForensics({ initialEvent }) {
  const initCase = initialEvent
    ? (MOCK_CASES.find(c => c.type === initialEvent.type) || MOCK_CASES[0])
    : null;
  const [selectedCase, setSelectedCase] = useState(initCase);

  if (selectedCase) {
    return <ForensicDetail caseData={selectedCase} onBack={() => setSelectedCase(null)} />;
  }

  const openCases = MOCK_CASES.filter(c => c.status === 'Open').length;
  const highSev   = MOCK_CASES.filter(c => c.severity === 'critical' || c.severity === 'high').length;
  const resolved  = MOCK_CASES.filter(c => c.status === 'Resolved').length;

  return (
    <div>
      <div className="sa-page-head" style={{ marginBottom: 20 }}>
        <div>
          <h1 className="sa-page-title">Forensics</h1>
          <p className="sa-page-sub">Detailed forensic investigation reports for flagged security incidents.</p>
        </div>
      </div>

      {/* Summary stats */}
      <div className="sa-stat-grid" style={{ marginBottom: 20 }}>
        {[
          { label: 'Open Cases',     value: openCases, cls: 'sa-stat-icon--red'   },
          { label: 'High Severity',  value: highSev,   cls: 'sa-stat-icon--amber' },
          { label: 'Resolved',       value: resolved,  cls: 'sa-stat-icon--green' },
          { label: 'Avg Resolution', value: '4h 12m',  cls: 'sa-stat-icon--blue'  },
        ].map((s, i) => (
          <div key={i} className="sa-stat-card">
            <p className="sa-stat-label">{s.label}</p>
            <span className="sa-stat-value" style={{ fontSize: '1.5rem' }}>{s.value}</span>
          </div>
        ))}
      </div>

      {/* Case cards */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {MOCK_CASES.map(c => {
          const cfg = SEVERITY_CFG[c.severity] || SEVERITY_CFG.info;
          return (
            <div
              key={c.id}
              className="sa-card"
              style={{ cursor: 'pointer' }}
              onClick={() => setSelectedCase(c)}
            >
              <div style={{ padding: '16px 20px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12, marginBottom: 10 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
                    <span style={{ fontFamily: 'Consolas, monospace', fontSize: '0.75rem', color: 'var(--sa-accent)' }}>{c.id}</span>
                    <span style={{ background: cfg.bg, color: cfg.color, border: `1px solid ${cfg.color}33`, borderRadius: 6, padding: '2px 8px', fontSize: '0.6875rem', fontWeight: 700 }}>{cfg.label}</span>
                    <span style={{
                      background: c.status === 'Open' ? 'var(--sa-red-dim)' : 'var(--sa-green-dim)',
                      color: c.status === 'Open' ? 'var(--sa-red)' : 'var(--sa-green)',
                      borderRadius: 6, padding: '2px 8px', fontSize: '0.6875rem', fontWeight: 700,
                    }}>{c.status}</span>
                  </div>
                  <span style={{ fontSize: '0.75rem', color: 'var(--sa-text-2)', whiteSpace: 'nowrap', flexShrink: 0 }}>{fmtDateTime(c.ts)}</span>
                </div>
                <p style={{ margin: '0 0 4px', fontWeight: 700, fontSize: '0.9375rem', color: 'var(--sa-text)' }}>{c.type}</p>
                <p style={{ margin: '0 0 12px', fontSize: '0.8125rem', color: 'var(--sa-text-2)', lineHeight: 1.5 }}>{c.desc}</p>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8 }}>
                  <span style={{ fontFamily: 'Consolas, monospace', fontSize: '0.75rem', color: 'var(--sa-text-2)' }}>{c.ip}</span>
                  <button className="sa-btn sa-btn--ghost sa-btn--sm">View Evidence <IcArrow /></button>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
