/**
 * Side-effect imports so `sequelize.sync({ alter: true })` creates only the minimal schema.
 */
require('./Role');
require('./User');
require('./School');
require('./SchoolAdmin');
require('./Teacher');
require('./Student');
require('./Class');
require('./Subject');
require('./ClassSubject');
require('./ClassAssistantTeacher');
require('./AcademicYear');
require('./Term');
require('./Grade');
require('./Attendance');
require('./GradingScheme');
require('./Room');
require('./Exam');
require('./Notification');
require('./OTP');
require('./SyllabusTopic');
require('./SecurityAuditLog');
require('./ForensicEvent');
require('./BroadcastAlert');
require('./SystemOpsAlert');
require('./SuperadminSettings');
require('./FeeCategory');
require('./Fee');
require('./Payment');
require('./Expense');
